### ISSUE TITLE
Creating single pages for the teams and projects

### ISSUE THREAD

**Issue by Palaash05** [Project-Club-IIITS/IOTA-website#2]
**Create individual pages for each team and each project:**
@Anuhya27 , @prichoms , @grumpy17 

**For team pages:**
- [ ] Contact respective teams and create the pages according to the responses.

**For Project pages:**
- Information will we provided by the maintainers.

**Tasks for design team:**
 @kajal1309 , @sampath6 

- [x] Design the proper layout for the page and provide it to the HTML & CSS team.
- [ ] Select suitable images for representation in the respective pages.
